version: '3.8'

services:

  server:
    volumes:
      - ./server:/app
      - ./server/output:/app/output
    image: jazzdd/alpine-flask:python3
    ports:
      - 5552:80

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5551:8080
    depends_on:
      - server
